import AppKit

/// Polls the system pasteboard for changes (there is no push notification for this on macOS)
/// and records new clippings into the shared ClipboardStore.
@MainActor
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private let maxImageDimension: CGFloat = 600
    private let pollInterval: TimeInterval = 0.5

    /// Markers password managers and similar apps put on pasteboard writes that shouldn't
    /// be kept in history (see nspasteboard.org).
    private static let concealedTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword")
    ]

    private init() {}

    func start() {
        lastChangeCount = NSPasteboard.general.changeCount
        refreshAccessStatus()
        timer?.invalidate()
        let timer = Timer(timeInterval: pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.poll()
            }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Re-reads whether the user has denied Encore access to the pasteboard in Privacy &
    /// Security → Paste from Other Apps. Cheap, and never itself triggers an alert.
    func refreshAccessStatus() {
        let denied = NSPasteboard.general.accessBehavior == .alwaysDeny
        let store = ClipboardStore.shared
        if store.isPasteboardAccessDenied != denied {
            store.isPasteboardAccessDenied = denied
        }
    }

    /// Where the user can allow Encore to read the pasteboard.
    static func openPasteboardPrivacySettings() {
        if let url = URL(string: "x-apple.systempreferences:com.apple.settings.PrivacySecurity.extension?Privacy_Pasteboard") {
            NSWorkspace.shared.open(url)
        }
    }

    /// Call right after Encore itself writes to the pasteboard (e.g. to paste a saved
    /// clipping) so that write isn't captured again as a brand-new clipping.
    func resyncChangeCount() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        refreshAccessStatus()

        let store = ClipboardStore.shared
        guard store.isRecordingEnabled else { return }

        let frontApp = NSWorkspace.shared.frontmostApplication
        if let bundleID = frontApp?.bundleIdentifier, store.isIgnored(bundleID: bundleID) {
            return
        }

        if store.ignoresConcealedContent,
           pasteboard.types?.contains(where: Self.concealedTypes.contains) == true {
            return
        }

        guard let clipping = makeClipping(from: pasteboard, sourceApp: frontApp) else { return }
        store.addClipping(clipping)
        SmartTitler.shared.enqueue(clipping.id)
        NotificationCenter.default.post(name: .clipboardDidRecordClipping, object: nil)

        if store.playSoundOnCopy {
            NSSound(named: "Tink")?.play()
        }
    }

    private func makeClipping(from pasteboard: NSPasteboard, sourceApp: NSRunningApplication?) -> Clipping? {
        let appName = sourceApp?.localizedName
        let bundleID = sourceApp?.bundleIdentifier

        if let images = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let image = images.first {
            let resized = image.resized(maxDimension: maxImageDimension)
            guard let data = resized.pngData() else { return nil }
            let label = "Image (\(Int(image.size.width))\u{00D7}\(Int(image.size.height)))"
            return Clipping(kind: .image, text: label, imageData: data, sourceAppName: appName, sourceBundleID: bundleID)
        }

        let fileReadingOptions: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: fileReadingOptions) as? [URL],
           !urls.isEmpty {
            return Clipping(kind: .fileURL, fileURLs: urls, sourceAppName: appName, sourceBundleID: bundleID)
        }

        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return Clipping(kind: .text, text: string, sourceAppName: appName, sourceBundleID: bundleID)
        }

        return nil
    }
}
